export const buses = [
  {
    id: '101',
    name: 'Green Line',
    route: ['dhaka', 'chittagong', 'comilla'],
    departureTime: '8.30 am',
    arrivalTime: '2.00 pm',
    busType: 'AC',
    busClass: 'Business',
    startingPoint: 'panthapath',
    endpoint: 'halishahor',
    company: 'green line limited',
    seatFair: 1200,
  },
  {
    id: '102',
    name: 'London Express',
    route: ['dhaka', 'tangail', 'sirajgonj', 'bogura', 'rangpur', 'dinajpur'],
    departureTime: '9.00 am',
    arrivalTime: '2.30 pm',
    busType: 'AC',
    busClass: 'Business',
    startingPoint: 'panthapath',
    endpoint: 'nasirabad',
    company: 'London Express',
    seatFair: 1000,
  },
  {
    id: '103',
    name: 'Hanif',
    route: ['dhaka', 'chittagong', 'comilla'],
    departureTime: '10.00',
    arrivalTime: '3.00 pm',
    busType: 'AC',
    busClass: 'Business',
    startingPoint: 'panthapath',
    endpoint: 'nasirabad',
    company: 'Hanif Enterprise',
    seatFair: 1000,
  },
];
